ktor:
  application:
    modules:
      - com.schoolarium.ApplicationKt.module
  deployment:
    port: 8080

database:
  url: $DB_URL
  driver: $DB_DRIVER
  username: $DB_USERNAME
  password: $DB_PASSWORD