name: Build and Deploy on Tag

on:
  push:
    tags:
      - 'v*.*.*' # Se activa con tags que sigan semver

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v5.0.0
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build Fat JAR
        run: ./gradlew buildFatJar

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: schoolarium
          path: build/libs/schoolarium.jar

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v3
        with:
          name: schoolarium

      - name: Deploy to AWS Ubuntu via SSH
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "schoolarium.jar"
          target: "/home/ubuntu/app/"

      - name: Restart Systemd Service
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            sudo systemctl stop schoolarium || true
            sudo systemctl start schoolarium
            sudo systemctl status schoolarium